# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.8
loader_version=0.17.2

## Mod Properties

mod_id=hexxit_gear_weaponry
mod_version=1.0.0
maven_group=net.nova.hexxit_gear_weaponry
mod_name=Hexxit Gear Weaponry
mod_license=MIT
mod_authors=ImVeryBad
mod_description=Hexxit Gear Weaponry is an addon for the mod Hexxit Gear R, adding weapons for the four armors sets (Scale, Tribal, Thief and Sage). Each with different abilities while are used with their armor sets.

## Dependencies
fabric_version=0.132.0+1.21.8
modmenu_version=15.0.0-beta.3
hgr_version=7JspdHTl
hgr_version_range=[1.0.0,)