# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties

minecraft_version=26.2
minecraft_version_range=[26.2]

neo_version=26.2.0.6-beta

## Mod Properties

mod_id=hexxit_gear_weaponry
mod_name=Hexxit Gear Weaponry
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.nova.hexxit_gear_weaponry
mod_authors=ImVeryBad, Foxirion
mod_description=Hexxit Gear Weaponry is an addon for the mod Hexxit Gear R, adding weapons for the four armors sets (Scale, Tribal, Thief and Sage). Each with different abilities while are used with their armor sets.

## Dependencies

hgr_version=geyYVMx4
hgr_version_range=[1.0.0,)