license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/Starexify/HexxitGearWeaponry"
issueTrackerURL="https://github.com/Starexify/HexxitGearWeaponry/issues"
logoFile= "hgw_logo.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="hexxit_gear"
    type="required"
    versionRange="${hgr_version_range}"
    ordering="NONE"
    side="BOTH"